Repository Takhi-mn/frontend, pull requests merged in 2024-04, with the labels that each got.

#37 blog page with id
  src/app/[locale]/blog/[id]/page.tsx
  src/app/[locale]/blog/components/allBlogPage/index.tsx
  src/app/[locale]/blog/components/blogById/blogComment.tsx
  src/app/[locale]/blog/components/blogById/blogPage.tsx
  src/app/[locale]/blog/components/blogById/writeCommentSection.tsx
  src/app/[locale]/blog/page.tsx
  src/assets/blog/userImage.png
  src/assets/index.ts
  src/components/blogSection/BlogCard.tsx
  src/components/blogSection/index.tsx
  src/data/blog/index.ts
  src/types/blog.ts
Labels: good first issue

#38 35 news page
  src/app/[locale]/globals.css
  src/app/[locale]/layout.tsx
  src/app/[locale]/tourism/booking/components/TourCard.tsx
  src/app/[locale]/tourism/booking/components/TourPath.tsx
  src/app/[locale]/tourism/components/CampMenu.tsx
  src/app/[locale]/tourism/page.tsx
  src/components/Footer.tsx
  src/components/MyDrawer.tsx
  src/components/NavbarNew.tsx
  src/components/Subscribe.tsx
  src/components/donateSection/DonateCard.tsx
  src/components/heroSection/MainLoader.tsx
  src/components/heroSection/backgroundVideo.tsx
  src/components/heroSection/index.tsx
  src/components/ui/button.tsx
  src/components/ui/drawer.tsx
  src/context/DataProvider.tsx
  src/data/index.ts
  src/lib/nameConverter.ts
  src/types/backend.ts
Labels: duplicate

#47 page datas
  src/app/[locale]/about-us/components/about-us-page.tsx
  src/app/[locale]/about-us/components/about-us-section.tsx
  src/app/[locale]/about-us/components/goal-and-mission-section.tsx
  src/app/[locale]/about-us/components/goal-section.tsx
  src/app/[locale]/about-us/components/mission.tsx
  src/app/[locale]/about-us/components/takhi-team-section.tsx
  src/app/[locale]/about-us/page.tsx
  src/app/[locale]/about-us/takhi-team/components/takhi-team.tsx
  src/app/[locale]/about-us/takhi-team/components/team-member.tsx
  src/app/[locale]/about-us/takhi-team/page.tsx
  src/app/[locale]/globals.css
  src/app/[locale]/our-work/components/footerWorkPage.tsx
  src/app/[locale]/our-work/components/learnMoreSection.tsx
  src/app/[locale]/our-work/components/ourWorkPage.tsx
  src/app/[locale]/our-work/local-sustainable-development/components/section-1.tsx
  src/app/[locale]/our-work/local-sustainable-development/components/section-2.tsx
  src/app/[locale]/our-work/local-sustainable-development/components/section-3.tsx
  src/app/[locale]/our-work/local-sustainable-development/components/section-4.tsx
  src/app/[locale]/our-work/local-sustainable-development/components/section-hero.tsx
  src/app/[locale]/our-work/local-sustainable-development/page.tsx
  src/app/[locale]/our-work/major-achievements/page.tsx
  src/app/[locale]/our-work/natioanal-park-management/components/section-1.tsx
  src/app/[locale]/our-work/natioanal-park-management/components/section-hero.tsx
  src/app/[locale]/our-work/natioanal-park-management/page.tsx
  src/app/[locale]/our-work/page.tsx
  src/app/[locale]/our-work/takhi-conservation-programs/components/card-photo.tsx
  src/app/[locale]/our-work/takhi-conservation-programs/components/graph-data-section.tsx
  src/app/[locale]/our-work/takhi-conservation-programs/components/hero-section.tsx
  src/app/[locale]/our-work/takhi-conservation-programs/components/intro-section.tsx
  src/app/[locale]/our-work/takhi-conservation-programs/components/map-section-1.tsx
  src/app/[locale]/our-work/takhi-conservation-programs/components/map-section.tsx
  src/app/[locale]/our-work/takhi-conservation-programs/components/pageComponent.tsx
  src/app/[locale]/our-work/takhi-conservation-programs/components/photo-section-reintro.tsx
  src/app/[locale]/our-work/takhi-conservation-programs/components/photo-slider-section.tsx
  src/app/[locale]/our-work/takhi-conservation-programs/page.tsx
  src/app/[locale]/our-work/wild-life-conservation/page.tsx
  src/app/[locale]/ourwork/local-sustainable-development/page.tsx
  src/app/[locale]/ourwork/natioanal-park-management/page.tsx
  src/app/[locale]/ourwork/re-introduction/components/card-photo.tsx
  src/app/[locale]/ourwork/re-introduction/components/intro-section.tsx
  src/app/[locale]/ourwork/re-introduction/components/map-section.tsx
  src/app/[locale]/ourwork/re-introduction/components/photo-slider-section.tsx
  src/app/[locale]/ourwork/re-introduction/page.tsx
  src/app/[locale]/ourwork/wild-life-conservation/components/photo-slider-section.tsx
  src/components/PartnerSection.tsx
  src/components/contactSection/components/locationSection.tsx
  src/components/contactSection/components/phoneSection.tsx
  src/components/contactSection/components/smsSection.tsx
  src/components/contactSection/contactsSection.tsx
  src/components/mapSection/index.tsx
  src/components/photoSlider/index.tsx
  src/components/photoSlider/photoSliderSmall.tsx
  src/context/DataProvider.tsx
  src/types/backend.ts
  src/types/member.ts
Labels: documentation

#52 data ourwork done
  src/app/[locale]/about-us/components/about-us-section.tsx
  src/app/[locale]/about-us/components/takhi-team-section.tsx
  src/app/[locale]/our-work/community-engagement/components/page-comp.tsx
  src/app/[locale]/our-work/community-engagement/components/section-1.tsx
  src/app/[locale]/our-work/community-engagement/components/section-2.tsx
  src/app/[locale]/our-work/community-engagement/components/section-3.tsx
  src/app/[locale]/our-work/community-engagement/components/section-4.tsx
  src/app/[locale]/our-work/community-engagement/components/section-hero.tsx
  src/app/[locale]/our-work/community-engagement/page.tsx
  src/app/[locale]/our-work/components/learnMoreSection.tsx
  src/app/[locale]/our-work/national-park-management/components/page-comp.tsx
  src/app/[locale]/our-work/national-park-management/components/section-1.tsx
  src/app/[locale]/our-work/national-park-management/components/section-hero.tsx
  src/app/[locale]/our-work/national-park-management/page.tsx
  src/app/[locale]/our-work/research-and-monitoring-program/components/heroSection.tsx
  src/app/[locale]/our-work/research-and-monitoring-program/components/mobile-section.tsx
  src/app/[locale]/our-work/research-and-monitoring-program/components/page-comp.tsx
  src/app/[locale]/our-work/research-and-monitoring-program/components/slider-section.tsx
  src/app/[locale]/our-work/research-and-monitoring-program/components/style.css
  src/app/[locale]/our-work/research-and-monitoring-program/components/test.tsx
  src/app/[locale]/our-work/research-and-monitoring-program/page.tsx
  src/app/[locale]/our-work/takhi-conservation-programs/components/pageComponent.tsx
  src/components/ourWorkSelector/index.tsx
  src/components/ourWorkSelector/ourWorkPageCard.tsx
Labels: documentation

#56 rdy deploy
  src/app/[locale]/about-us/takhi-team/components/takhi-team.tsx
  src/app/[locale]/about-us/takhi-team/components/teamSelector.tsx
  src/components/PartnerSection.tsx
  src/components/contactSection/components/locationSection.tsx
  src/components/contactSection/components/phoneSection.tsx
  src/components/contactSection/components/smsSection.tsx
  src/components/contactSection/contactsSection.tsx
  src/components/ourWorkSelector/index.tsx
  src/components/ourWorkSelector/ourWorkPageCard.tsx
  src/context/DataProvider.tsx
Labels: bug
